apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysql-server
  name: mysql-server
spec:
# rds kullandıgımızda bu 2 satırı yazdık ve mysql-deploymen.yaml dosyasını sildik
  type: ExternalName
  externalName: petclinic.c9migwi4k32r.us-east-1.rds.amazonaws.com
# mysql-deployment kullandıgımızda asagıdaki kısmı kullandık
  # ports:
  #   - name: "3306"
  #     port: 3306
  #     targetPort: 3306
  # selector:
  #   io.kompose.service: mysql-server
